title: Cherrie Kwok
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
logo: https://user-images.githubusercontent.com/45428531/100288083-eec2f300-2f43-11eb-9f0f-e8588466444c.jpg
show_downloads: true
description: Elizabeth Arendall Tilney and Schuyler Merritt Tilney Jefferson Fellow and PhD Candidate, Department of English, University of Virginia
theme: jekyll-theme-minimal
google_analytics: UA-179062687-1
plugins:
  - jemoji





